#!/bin/bash

run_migration () {
    export TABLE_NAME=$1
    export DDL_PATH=$2
    message="Add ${TABLE_NAME}"
    echo "[DEBUG] Starting migration message: $message"
    alembic revision -m "$message"
}

# Update the code below with your table names and ddl paths.
run_migration foo ddls/foo.sql
run_migration bar ddls/bar.sql

