#!/bin/bash

run_migration () {
    export TABLE_NAME=$1
    export DDL_PATH=$2
    message="Add ${TABLE_NAME}"
    echo "[DEBUG] Starting migration message: $message"
    alembic revision -m "$message"
}

run_migration foo_table /tmp/ddl.sql

